service: pre-token-lambda

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  logRetentionInDays: 14
  stackTags:
    project: datarock-platform
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'cognito-idp:AdminGetUser'
          Resource: { "Fn::Sub": "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${cf:datarock-infrastructure-${self:provider.stage}.UserPool}" }

functions:
  preTokenGeneration:
    handler: src/handler.preTokenGeneration
    events:
      - cognitoUserPool:
          pool: datarock-users-${self:provider.stage}
          trigger: PreTokenGeneration
          existing: true
    environment:
      METADATA_API_URL: https://image-metadata-api-serverless.${self:provider.stage}.datarock.com.au
      METADATA_API_KEY: ${ssm:/apig/platform-infrastructure/${self:provider.stage}/api-key~true}
      COGNITO_USER_POOL_ID: ${cf:datarock-infrastructure-${self:provider.stage}.UserPool}
    timeout: 10
plugins:
  - serverless-bundle

