service: pre-token-generation-lambda-trigger

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  preTokenGeneration:
    handler: handler.preTokenGeneration
    events:
      - cognitoUserPool:
          pool: MyUserPool # TODO: read from config
          trigger: PreTokenGeneration
          existing: true
